### ISSUE TITLE
Last 90 Days button breaks the site

### ISSUE THREAD

**Issue by BigManatee** [CodeFoodPixels/emptyjar#15]
I've been searching for a simple self hosted analytics that isn't such a pain and found this from inspecting your website! *sorry*

It's a godsend and works like a dream, just the `Last 90 days` button causes issues due to `Cannot read properties of undefined (reading 'value')` coming from [reducers.js#88](https://github.com/CodeFoodPixels/emptyjar/blob/master/client/reducers.js#L88).
For some reason, `views` doesn't contain `dateString` (the current date).

I'm sure you're aware of it but I thought I'd let you know anyway, I've bodged _(?)_ mine by changing [components/RangePicker.js#L118](https://github.com/CodeFoodPixels/emptyjar/blob/master/client/components/RangePicker.js#L118) to `new Date(Date.now() + oneDay)` which does make it work so I'm counting it as a win.

**Comment by CodeFoodPixels** [comment]
Haha, I've been planing on actually launching this at some point, I've just not had the time to get it polished. Happy that you're using it!

I'll have a look into the issue, thanks for reporting!

**Comment by BigManatee** [comment]
You definitely should, my usage with it so far has been extremely pleasant!
I also hit a snag with `npm install`, `sqlite3@4.1.0` was causing problems but a simple install of `sqlite3@5.0.2` solved that for me, just so you're aware of that, too!

**Comment by CodeFoodPixels** [comment]
So I think the initial error was caused by timezones 🤦‍♂️ 

As for the sqlite issue, what platform were you having an issue with? OS, node version etc

**Comment by BigManatee** [comment]
Oh really? I was far off with my bodge then 👀
Server info:
os: `Ubuntu 21.04 (GNU/Linux 5.11.0-36-generic x86_64)`
node: `v16.10`
npm: `6` something then updated to `8.3.2`

The npm logs are gone so I can't provide the exact thing but it was essentially the below (just tried npm install on my local windows machine, same error)

```log
3268 error node-pre-gyp info check checked for "C:\Users\iamt\Desktop\analytics\node_modules\sqlite3\lib\binding\node-v93-win32-x64\node_sqlite3.node" (not found)
3268 error node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v93-win32-x64.tar.gz
3268 error node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v93-win32-x64.tar.gz
3268 error node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v93-win32-x64.tar.gz
3268 error node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.0 and node@16.13.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
3268 error node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v93-win32-x64.tar.gz
```

**Comment by CodeFoodPixels** [comment]
So that error looks like it's failing to get a prebuilt version of the
binary. I've updated it to the latest one.

All the fixes are pushed up, feel free to update.

I saw that you've changed the colours too! I like the idea of making it
configurable, so I might have a go at that

**Comment by BigManatee** [comment]
I've pulled your changes, still working like a treat and nicer looking buttons now!

I saw the colours were already in css variables so I thought I'd tailor to myself, may be kinda cool to offer some simple alternative themes along with it.
Nice one on the footer linking to the repo, too!
